name: 'Ecsact SDK'
description: 'Greet someone'
runs:
  using: "composite"
  steps:
    - name: Download Ecsact SDK
      if: runner.os == 'Windows'
      run: "gh -R ecsact-dev/ecsact_sdk release download -p '*.msix' -D ${{ github.action_path }}"

    - name: Install Ecsact SDK
      shell: pwsh
      if: runner.os == 'Windows'
      run: "Add-AppPackage -Path ((Get-ChildItem -Path ${{ github.action_path }} -Filter *.msix | Select-Object -first 1).name)"

