name: 'Ecsact SDK'
description: 'Greet someone'
runs:
  using: "composite"
  steps:
    - name: Install Ecsact SDK
      if: runner.os == 'Windows'
      shell: pwsh
      run: "${{ github.action_path }}\\ecsact-install-windows.ps1"
      env:
        GITHUB_TOKEN: ${{ github.token }}

